version: '3'

networks: 
  db:
  web:

services:
  # desafio-backend:
  #   image: desafio-backend
  #   build: .
  #   environment:
  #     NODE_ENV: dev
  #   ports:
  #     - 3001:3000
  #   networks: 
  #     - web
  #     - db
  mongo:
    image: mongo
    container_name: mongodb-desafio
    restart: always
    ports:
      - 27017:27017
    networks:
      - db